step-1
RenatGrishin/react-burger pull request #1
Opened 2022-10-02 21:06 UTC by RenatGrishin

Верстка компонентов

2022-10-03 18:00 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа. Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодцы!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;

### **Но есть несколько замечаний, которые нужно исправить:**

- В верстке начинки и булки перепутаны местами.

- Во многих компонентах не описаны `propTypes`. Также напоминаю `propTypes` для ингредиента должны быть описаны через `shape`. Подробнее про `propTypes`: https://ru.react.js.org/docs/typechecking-with-proptypes.html. И напоминаю, в описании propTypes, где это требуется, нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается.

- Поправьте семантику в компоненте `AppHeader`

- Исправить замечания в компоненте `BurgerConstructor`.

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-10-03 21:41 UTC, RenatGrishin commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +                            findCategory('main').map( elem => <Ingredient
До UseMemo еще не добрался. Добирусь до этой темы сегодня

2022-10-04 05:06 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +                            findCategory('main').map( elem => <Ingredient
Пока что, не обязательно его использовать. Можно просто сделать фильтр, а в финальной сдаче уже обернуть всё что нужно)

2022-10-04 16:53 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодцы!**

- Почти все замечания с 1 ревью, были исправлены.

### **Но есть несколько новых замечаний, которые нужно исправить:**

- Проект не запускается и не собирается. Чтобы это воспроизвести, попробуйте склонировать свой репозиторий, и перейти в ветку пул-реквеста. Вот скрин ошибок: 
   
   ![image](https://user-images.githubusercontent.com/70164458/193879647-e4fc0654-6350-4f69-a57b-386a6417a17a.png)

- Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации `create-react-app`.

- Удалить неиспользуемые файлы стилей (у `AppHeader`). А также удалить компонент `IngredientCustom`.

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде. Если возникнут какие-либо вопросы, то буду рад на них ответить_**

2022-10-04 16:53 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  };
**Надо исправить:** Локальные переменные будут сбрасываться при каждом рендеринге, тогда как состояние будет обновляться.
Вот неплохое обсуждение на эту тему: https://stackoverflow.com/questions/58252454/react-hooks-using-usestate-vs-just-variables.

также в прошлом ревью я вам показывал как лучше вытащить ингредиенты и булку.

```js
  const bun = constructorIngredients.find(
    (ingredient) => ingredient.type === "bun" && ingredient._id === list.bun
  );
  const ingredients = constructorIngredients.filter(
    (ingredient) => ingredient.type !== "bun" && list.ingredients.includes(ingredient.id)
  );
```

А стоимость попробуйте реализовать сами, с помощью `ingredients` и `bun`. Но помните, что булок у на 2 штуки, поэтому и стоимость булки будет - `* 2`.

2022-10-04 16:53 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    });
**Надо исправить:** Здесь больше подходит метод `forEach`, т.к мы не создаём новый массив от массива `list.ingredients`.
forEach - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
map - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/map

2022-10-04 16:53 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  ),
**Надо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте.

**Можно лучше**
во многих компонентах дублируется описание PropTypes ингредиента

Лучше вынести его в отдельный файл (можно создать файл prop-types.js в корне src) и переиспользовать описание пропсов ингрединта, а не дублировать

2022-10-04 19:42 UTC, RenatGrishin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  };
Запись ингредиентов поправил
Посчет цены поправил.
`state.price =
      state.bun.price * 2 +
      state.ingredients.reduce((sum, i) => sum + i.price, 0);`

2022-10-04 19:49 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  };
Как я и говорил ранее, лучше просто сделать отдельные переменные: `bun`, `ingredients`, `sum`. Так вам будет легче манипулировать с ними, а в дальнейшем, это всё нужно будет обернуть в useMemo.  Я уже писал, к чему приведёт матирование, и использование локального state .

2022-10-04 19:54 UTC, RenatGrishin commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +                            findCategory('main').map( elem => <Ingredient
Вынес все в стейт, в категории

2022-10-04 19:54 UTC, RenatGrishin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    });
Упустил момент, поправил

2022-10-04 19:55 UTC, RenatGrishin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  ),
Сделал обязательную проверку в компонентах, и вынес это шаблон в отдельный подключаемый файл

2022-10-05 07:29 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Замечания, исправляйте уже в финальной сдаче. Т.е в след раз сдаёте уже новый pull-request `step-2`.

### **Замечания с прошлого ревью не исправлены, но там критично только 1 замечание, с запуском проекта. Исправьте его, и можете мерджить этот пулл-реквест.**

- Проект не запускается и не собирается. Чтобы это воспроизвести, попробуйте склонировать свой репозиторий, и перейти в ветку пул-реквеста. Вот скрин ошибок: 
   
   ![image](https://user-images.githubusercontent.com/70164458/193879647-e4fc0654-6350-4f69-a57b-386a6417a17a.png)

   Я предполагаю, что у вас похожая проблема.
   https://stackoverflow.com/questions/17622906/updating-file-names-in-git-from-camel-case-to-all-lower-case.

- Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации `create-react-app`.

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде. Если возникнут какие-либо вопросы, то буду рад на них ответить_**

2022-10-05 07:29 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  }
**Можно лучше:** Перед отпавкой, убедитесь, что весь неиспользуемый код удалён.

2022-10-07 23:24 UTC, closed without merging