stars step 2
RenatGrishin/react-burger pull request #2
Opened 2022-10-07 23:45 UTC by RenatGrishin

2022-10-07 23:49 UTC, RenatGrishin commented
Поправил предыдущие замечания.

Проект не собирался, так как у CSS в названии я заменил регистры первых букв на маленькие. При замене файлов, Windows файлы заменил, но регистры оставил болшими.

2022-10-08 20:28 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодцы!**

### **Но есть несколько новых замечаний, которые нужно исправить:**

- По чек-листу требуется чтобы у вас были компоненты `Modal` и `ModalOverlay`, У вас же всё это находиться в 1 компоненте - ModalOverlay. `ModalOVerlay` по чек-листу должен быть просто фоновой подложкой под модальным окном. Также модальные окна, должны тоже закрываться при клике на `ModalOverlay`.

- Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации `create-react-app`.

- Поправить работу с запросами.

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде. Если возникнут какие-либо вопросы, то буду рад на них ответить_**

2022-10-08 20:28 UTC, ArslanDev666 commented on src/components/ModalOverlay/ModalOverlay.jsx
> +            )}
**Можно лучше:** лучше передавать пропс `children` компоненту `Modal`. И туда прокидывать либо, то что нужно, потому что у нас может быть очень много видов модалок, и писать под каждый вид условие, не оч производительно.

2022-10-08 20:28 UTC, ArslanDev666 commented on src/components/ModalOverlay/ModalOverlay.jsx
> +  }
**Надо исправить:** По чек-листу, требуется реализовать закрытие только по нажатию `Esc`клавише.

2022-10-08 20:28 UTC, ArslanDev666 commented on src/App.tsx
> +    });
**Надо исправить**
вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте.

**Можно лучше**
вызывать скрытие индикатора загрузки слудеует в блоке `finally`, а не дублировать в `then` и `catch`
[https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)

2022-10-08 20:28 UTC, ArslanDev666 commented on src/components/Ingredient/Ingredient.jsx
> +          }}
**Можно лучше:** Лучше вынести обработчик событий в отдельную функцию.

2022-10-10 09:26 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодцы!**

### **Но есть несколько новых замечаний, которые нужно исправить.**

### **также несколько замечаний отмечены в коде.**

- Поправить обработчик событий у модальных окон.

- У вас есть баг, если открыть модальное окно детали ингредиенты, и нажать на `esc`, то откроется другое модальное окно детали заказа.

- Убрать синюю обводку у блоков, эта обводка на макете нужна только что бы сделать описание поясняющее к этому блоку (в компоненте OrderDetails у иконки).

- В директории `components` должен быть компонент App. Компонент `App`, как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

2022-10-10 09:26 UTC, ArslanDev666 commented on src/components/ModalOverlay/ModalOverlay.jsx
> +  return ReactDOM.createPortal(
Надо исправить: здесь не нужно создавать портал. Структура Компонента modal должна быть примерно такая:
```js
  <>
    <div className={styles.modal}>{...}</div>
    <ModalOverlay onClick={onClose} />
  </>,
```

Надо исправить: У ModalOverlay не должно быть children, это просто компонент подложки а не контейнер

2022-10-10 09:26 UTC, ArslanDev666 commented on src/App.tsx
> +    connectBurgerApi( setData, setLoadingData, setStatus );
**Можно лучше :** Нежелательно мутировать что-то или менять в запросах, запрос должен просто делать запрос, а не ставить лоадеры, или какие-то данные. Лучше сделать вот так: 
```js 
  const [ingredients, setIngredients] = useState([]);
  const [ingredientsLoading, setIngredientsLoading] = useState(true);

  useEffect(() => {
    getIngredients()
      .then(setIngredients)
      .catch(() => alert("Во время загрузки ингредиентов произошла ошибка."))
      .finally(() => setIngredientsLoading(false));
  }, []);
```

2022-10-10 19:02 UTC, RenatGrishin commented on src/components/Modal/Modal.jsx
> +  });
Имправил

2022-10-10 19:35 UTC, RenatGrishin commented on src/components/ModalOverlay/ModalOverlay.jsx
> +  return ReactDOM.createPortal(
Поправил.

2022-10-10 20:20 UTC, RenatGrishin commented on src/App.tsx
> +    connectBurgerApi( setData, setLoadingData, setStatus );
Поправил

2022-10-11 16:00 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодцы, задание принято. Удачи в дальнейшем обучении!**

### **Сделает код лучше.**

- в следующих заданиях, поправьте код, чтобы ошибок в консоли не было ошибок и варнингов. 2 ошибка возникает, при открытии OrderDetails модального окна.
  
  ![image](https://user-images.githubusercontent.com/70164458/195141897-5e84dfd0-cfe7-43e7-bad8-d3953040baab.png)

- поправьте компонент Modal.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

2022-10-11 16:00 UTC, ArslanDev666 commented on src/components/App/App.tsx
> +      setLoadingData(false);
**Можно лучше:** Можно применить деструктуризацию, если мы точно знаем что там будет поле data.

2022-10-11 16:00 UTC, ArslanDev666 commented on src/components/Modal/Modal.jsx
> +      {props.show && (
**Надо исправить. По хорошему вам ещё нужно это исправить. но т.к уже пошла 7 итерация, то исправите к след заданию. Сейчас это не очень критическое замечание, но в будущем исправьте обязательно.**

не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```
{isOpen && (
    компонент открываемого попапа
)}
``

2022-10-11 16:00 UTC, ArslanDev666 commented on src/components/Modal/Modal.jsx
> +  }, []);
**Можно лучше:** лучше занести функцию escFunction в useEffect, а также указать в зависимостях props.onClose. Перенос функции сделает код более оптимизированным, функция не будет каждый раз создаваться при ререндере. А передавать зависимости, нужно чтобы useEffect понял, когда нужно выполнить cb и чтобы данные всегда были в актуальном состоянии.

2022-10-15 16:47 UTC, merged